version: '3.3'

services:

  sample:
    container_name: graham_colton_coding_assignment11
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 7555:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
